### ISSUE TITLE
Error when using ariga/atlas-action/migrate/apply@v1 with PostgreSQL

### ISSUE THREAD

**Issue by WilliamSoler** [ariga/atlas-action#144]
When using the [Apply GitHub Action](https://atlasgo.io/integrations/github-actions#arigaatlas-actionmigrateapply):

```
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ariga/setup-atlas@v0
      - name: Deploy Atlas Migrations
        uses: ariga/atlas-action/migrate/apply@v1
        with:
          url: ${{ secrets.DATABASE_URL }}
          dir: db/schema.hcl
```
          
Where ${{ secrets.DATABASE_URL }} = postgres://db_user:Pass123@dpg-cnvc02un7f5s7394kce0-a.frankfurt-postgres.render.com/name_db

Which seems to be a [valid Postgres URL](https://atlasgo.io/concepts/url)

I get the following error:

> Run ariga/atlas-action/migrate/apply@v1
> Using version v1
> Downloading atlas-action binary: https://release.ariga.io/atlas-action/atlas-action-v1
> **Error: Error: unsupported driver ""**
> **Error: The process exited with code 1**
          
To see if my DATABASE_URL secret was the problem I tried to run manually the command `atlas schema inspect`
in the following way:
```
  test-atlas-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Atlas CLI
        run: curl -sSf https://atlasgo.sh | sh


      - name: Inspect Database Schema
        run: atlas schema inspect --url ${{ secrets.DATABASE_URL }}
        env:
          ATLAS_NO_COLOR: "true"
```

And it worked successfully without error.

Thank you in advance, and let me know if more information is required.

**Comment by rotemtam** [comment]
If your dir resides on the local file system, prefix the path with file://

**Comment by WilliamSoler** [comment]
Thank you very much, that worked 🙏🏼 I was just a little confused by the error message.

**Comment by WilliamSoler** [comment]
Sorry to bother you again. After making the change you suggested:

`dir: file://db`

It did not show any error and created the **atlas_schemas_revisions** Postgres schema:
![image](https://github.com/ariga/atlas-action/assets/114860454/e3e29518-15b1-435e-852d-7ece3fbb0084)

 but it did not create my schema or table (or created the table in another schema), also it did not create an entry on the table **atlas_schema_revisions** where my **db/schema.hcl** file looks like:
```
schema "nameschema" {}

table "countries" {
  schema = schema.nameschema
  column "id" {
    type = int
     null = false

  }
  column "name" {
    type = varchar(100)
    null = false
  }
    primary_key {
    columns = [
      column.id
    ]
  }
}
```

Thank you again.

**Comment by ronenlu** [comment]
`migrate/apply` takes in the `dir` input, url to migration directory. 
Since your `db/schema.hcl` file is not a path to migration directory, the job results in no change to the DB.

In order to convert your schema file to migration dir, you can run the next [command](https://atlasgo.io/versioned/diff):
`atlas migrate diff --dev-url "docker://postgres/15/dev?search_path=public"  --to "file://db/schema.hcl" --dir "file://db/migrations"`
This will result in creation of migration directory in the `db/migrations` path.

Now run can the action when passing the dir path  to dir input:
```
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ariga/setup-atlas@v0
      - name: Deploy Atlas Migrations
        uses: ariga/atlas-action/migrate/apply@v1
        with:
          url: ${{ secrets.DATABASE_URL }}
          dir: "file://db/migrations"
```
